version: '3.7'

volumes:
    db-data:

services:
    postgres:
        container_name: app-postgres
        image: postgres:12.5-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: random_password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - 5432:5432
        networks:
            - app-network

    adminer:
        container_name: app-adminer
        image: adminer:4.7.8-standalone
        ports:
            - 8002:8080
        networks:
            - app-network
